apiVersion: monitoring.chronosphere.io/v1alpha1
kind: ChronosphereDashboard
metadata:
  labels:
    app.kubernetes.io/name: chronosphere-operator
    app.kubernetes.io/managed-by: kustomize
  name: chronospheredashboard-sample
spec:
  slug: controller-runtime-metrics
  name: "Controller Runtime Metrics"
  collection_slug: organize_later
  dashboard_json: >
    {
      "kind": "Dashboard",
      "spec": {
        "duration": "15m",
        "events": [],
        "layouts": [
          {
            "kind": "Grid",
            "spec": {
              "display": {
                "collapse": {
                  "open": true
                },
                "title": "Reconciliation Metrics"
              },
              "items": [
                {
                  "content": {
                    "$ref": "#/spec/panels/numberOfWorkersInUse-24"
                  },
                  "height": 8,
                  "width": 3,
                  "x": 0,
                  "y": 0
                },
                {
                  "content": {
                    "$ref": "#/spec/panels/totalReconciliationCountPerController-7"
                  },
                  "height": 8,
                  "width": 11,
                  "x": 3,
                  "y": 0
                },
                {
                  "content": {
                    "$ref": "#/spec/panels/reconciliationErrorCountPerController-6"
                  },
                  "height": 8,
                  "width": 10,
                  "x": 14,
                  "y": 0
                }
              ]
            }
          },
          {
            "kind": "Grid",
            "spec": {
              "display": {
                "collapse": {
                  "open": true
                },
                "title": "Work Queue Metrics"
              },
              "items": [
                {
                  "content": {
                    "$ref": "#/spec/panels/workQueueDepth-22"
                  },
                  "height": 8,
                  "width": 3,
                  "x": 0,
                  "y": 0
                },
                {
                  "content": {
                    "$ref": "#/spec/panels/secondsForItemsStayInQueueBeforeBeingRequestedP50P90P99-13"
                  },
                  "height": 8,
                  "width": 11,
                  "x": 3,
                  "y": 0
                },
                {
                  "content": {
                    "$ref": "#/spec/panels/workQueueAddRate-15"
                  },
                  "height": 8,
                  "width": 10,
                  "x": 14,
                  "y": 0
                },
                {
                  "content": {
                    "$ref": "#/spec/panels/unfinishedSeconds-23"
                  },
                  "height": 9,
                  "width": 3,
                  "x": 0,
                  "y": 8
                },
                {
                  "content": {
                    "$ref": "#/spec/panels/secondsProcessingItemsFromWorkQueueP50P90P99-19"
                  },
                  "height": 9,
                  "width": 11,
                  "x": 3,
                  "y": 8
                },
                {
                  "content": {
                    "$ref": "#/spec/panels/workQueueRetriesRate-17"
                  },
                  "height": 9,
                  "width": 10,
                  "x": 14,
                  "y": 8
                }
              ]
            }
          }
        ],
        "panels": {
          "numberOfWorkersInUse-24": {
            "kind": "Panel",
            "spec": {
              "display": {
                "name": "Number of workers in use"
              },
              "plugin": {
                "kind": "GaugeChart",
                "spec": {
                  "calculation": "LastNumber",
                  "thresholds": {
                    "steps": [
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": {
                    "abbreviate": true,
                    "kind": "Decimal"
                  }
                }
              },
              "queries": [
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "controller_runtime_active_workers{}",
                        "series_name_format": "{{controller}}"
                      }
                    }
                  }
                }
              ]
            }
          },
          "reconciliationErrorCountPerController-6": {
            "kind": "Panel",
            "spec": {
              "display": {
                "description": "Total number of reconciliation errors per controller",
                "name": "Reconciliation Error Count Per Controller"
              },
              "plugin": {
                "kind": "TimeSeriesChart",
                "spec": {
                  "legend": {
                    "position": "Bottom"
                  },
                  "y_axis": {
                    "unit": {
                      "abbreviate": true,
                      "kind": "Decimal"
                    }
                  }
                }
              },
              "queries": [
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "sum(rate(controller_runtime_reconcile_errors_total{}[5m])) by (controller)",
                        "series_name_format": "{{controller}}"
                      }
                    }
                  }
                }
              ]
            }
          },
          "secondsForItemsStayInQueueBeforeBeingRequestedP50P90P99-13": {
            "kind": "Panel",
            "spec": {
              "display": {
                "description": "How long in seconds an item stays in workqueue before being requested",
                "name": "Seconds For Items Stay In Queue (before being requested) (P50, P90, P99)"
              },
              "plugin": {
                "kind": "TimeSeriesChart",
                "spec": {
                  "legend": {
                    "position": "Bottom"
                  },
                  "y_axis": {
                    "unit": {
                      "abbreviate": true,
                      "kind": "Seconds"
                    }
                  }
                }
              },
              "queries": [
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "histogram_quantile(0.50, sum(rate(workqueue_queue_duration_seconds_bucket{}[5m])) by (name, le))",
                        "series_name_format": "P50 {{name}}"
                      }
                    }
                  }
                },
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{}[5m])) by (name, le))",
                        "series_name_format": "P90 {{name}}"
                      }
                    }
                  }
                },
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{}[5m])) by (name, le))",
                        "series_name_format": "P99 {{name}}"
                      }
                    }
                  }
                }
              ]
            }
          },
          "secondsProcessingItemsFromWorkQueueP50P90P99-19": {
            "kind": "Panel",
            "spec": {
              "display": {
                "description": "How long in seconds processing an item from workqueue takes.",
                "name": "Seconds Processing Items From WorkQueue (P50, P90, P99)"
              },
              "plugin": {
                "kind": "TimeSeriesChart",
                "spec": {
                  "legend": {
                    "position": "Bottom"
                  },
                  "y_axis": {
                    "unit": {
                      "abbreviate": true,
                      "kind": "Seconds"
                    }
                  }
                }
              },
              "queries": [
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "histogram_quantile(0.50, sum(rate(workqueue_work_duration_seconds_bucket{}[5m])) by (name, le))",
                        "series_name_format": "P50 {{name}}"
                      }
                    }
                  }
                },
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "histogram_quantile(0.90, sum(rate(workqueue_work_duration_seconds_bucket{}[5m])) by (name, le))",
                        "series_name_format": "P90 {{name}}"
                      }
                    }
                  }
                },
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{}[5m])) by (name))",
                        "series_name_format": "P99 {{name}}"
                      }
                    }
                  }
                }
              ]
            }
          },
          "totalReconciliationCountPerController-7": {
            "kind": "Panel",
            "spec": {
              "display": {
                "description": "Total number of reconciliations per controller",
                "name": "Total Reconciliation Count Per Controller"
              },
              "plugin": {
                "kind": "TimeSeriesChart",
                "spec": {
                  "legend": {
                    "position": "Bottom"
                  },
                  "y_axis": {
                    "unit": {
                      "abbreviate": true,
                      "kind": "Decimal"
                    }
                  }
                }
              },
              "queries": [
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "sum(rate(controller_runtime_reconcile_total{}[5m])) by (controller)",
                        "series_name_format": "{{controller}}"
                      }
                    }
                  }
                }
              ]
            }
          },
          "unfinishedSeconds-23": {
            "kind": "Panel",
            "spec": {
              "display": {
                "description": "How many seconds of work has done that is in progress and hasn''t been observed by work_duration.\nLarge values indicate stuck threads.\nOne can deduce the number of stuck threads by observing the rate at which this increases.",
                "name": "Unfinished Seconds"
              },
              "plugin": {
                "kind": "GaugeChart",
                "spec": {
                  "calculation": "LastNumber",
                  "thresholds": {
                    "steps": [
                      {
                        "color": "orange",
                        "value": 70
                      },
                      {
                        "color": "red",
                        "value": 85
                      }
                    ]
                  },
                  "unit": {
                    "abbreviate": true,
                    "kind": "Seconds"
                  }
                }
              },
              "queries": [
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "sum by (name) (rate(workqueue_unfinished_work_seconds{}[5m]))",
                        "series_name_format": "{{name}}"
                      }
                    }
                  }
                }
              ]
            }
          },
          "workQueueAddRate-15": {
            "kind": "Panel",
            "spec": {
              "display": {
                "name": "Work Queue Add Rate"
              },
              "plugin": {
                "kind": "TimeSeriesChart",
                "spec": {
                  "legend": {
                    "position": "Bottom"
                  },
                  "y_axis": {
                    "unit": {
                      "abbreviate": true,
                      "kind": "Decimal"
                    }
                  }
                }
              },
              "queries": [
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "sum(rate(workqueue_adds_total{}[5m])) by (name)",
                        "series_name_format": "{{name}}"
                      }
                    }
                  }
                }
              ]
            }
          },
          "workQueueDepth-22": {
            "kind": "Panel",
            "spec": {
              "display": {
                "name": "WorkQueue Depth"
              },
              "plugin": {
                "kind": "GaugeChart",
                "spec": {
                  "calculation": "LastNumber",
                  "thresholds": {
                    "steps": [
                      {
                        "color": "orange",
                        "value": 70
                      },
                      {
                        "color": "red",
                        "value": 85
                      }
                    ]
                  },
                  "unit": {
                    "abbreviate": true,
                    "kind": "Decimal"
                  }
                }
              },
              "queries": [
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "sum by (name) (workqueue_depth{})",
                        "series_name_format": "{{name}}"
                      }
                    }
                  }
                }
              ]
            }
          },
          "workQueueRetriesRate-17": {
            "kind": "Panel",
            "spec": {
              "display": {
                "description": "Total number of retries handled by workqueue",
                "name": "Work Queue Retries Rate"
              },
              "plugin": {
                "kind": "StatChart",
                "spec": {
                  "calculation": "LastNumber",
                  "sparkline": {},
                  "thresholds": {
                    "steps": [
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": {
                    "abbreviate": true,
                    "kind": "Decimal"
                  }
                }
              },
              "queries": [
                {
                  "kind": "DataQuery",
                  "spec": {
                    "plugin": {
                      "kind": "PrometheusTimeSeriesQuery",
                      "spec": {
                        "query": "sum(rate(workqueue_retries_total{}[5m])) by (name)",
                        "series_name_format": "{{name}}"
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        "variables": []
      },
      "spec_version": "1"
    }