apiVersion: v1
kind: ConfigMap
metadata:
    name: argocd-cm
    labels:
        app.kubernetes.io/name: argocd-cm
        app.kubernetes.io/part-of: argocd
data:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
    resource.customizations: |
        monitoring.chronosphere.io/*:
          health.lua: |
            hs = {
                status = "Progressing",
                message = "Update in progress"
            }
            if obj.status ~= nil then
                if obj.status.state ~= nil then
                    if obj.status.state == "Success" then
                        hs.status = "Healthy"
                        hs.message = obj.status.message
                    end
                    if obj.status.state == "" then
                        hs.status = "Missing"
                        hs.message = "Component state: Unknown."
                    end
                    if obj.status.state == "Failed" then
                        hs.status = "Degraded"
                        hs.message = obj.status.message
                    end
                end
                return hs
            end
            return hs
