// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Configv1MutingRule configv1 muting rule
//
// swagger:model configv1MutingRule
type Configv1MutingRule struct {

	// Optional comment that explains why the muting rule was created.
	Comment string `json:"comment,omitempty"`

	// Timestamp of when the MutingRule was created. Cannot be set by clients.
	// Read Only: true
	CreatedAt string `json:"created_at,omitempty"`

	// Timestamp of when the muting rule stops being active.
	EndsAt string `json:"ends_at,omitempty"`

	// Specify which series are silenced by the muting rule. Alerting series must
	// match all muting rule matchers to be silenced.
	// This value cannot be updated. Updates must specify the original value.
	LabelMatchers []*Configv1MutingRuleLabelMatcher `json:"label_matchers,omitempty"`

	// Required name of the MutingRule. May be modified after the MutingRule is created.
	Name string `json:"name,omitempty"`

	// Unique identifier of the MutingRule. If slug is not provided, one will be generated based of the name field. Cannot be modified after the MutingRule is created.
	Slug string `json:"slug,omitempty"`

	// Timestamp of when the muting rule becomes active.
	// This value cannot be updated. Updates must specify the original value.
	StartsAt string `json:"starts_at,omitempty"`

	// Timestamp of when the MutingRule was last updated. Cannot be set by clients.
	// Read Only: true
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this configv1 muting rule
func (m *Configv1MutingRule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabelMatchers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Configv1MutingRule) validateLabelMatchers(formats strfmt.Registry) error {
	if swag.IsZero(m.LabelMatchers) { // not required
		return nil
	}

	for i := 0; i < len(m.LabelMatchers); i++ {
		if swag.IsZero(m.LabelMatchers[i]) { // not required
			continue
		}

		if m.LabelMatchers[i] != nil {
			if err := m.LabelMatchers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("label_matchers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("label_matchers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this configv1 muting rule based on the context it is used
func (m *Configv1MutingRule) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLabelMatchers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Configv1MutingRule) contextValidateCreatedAt(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "created_at", "body", string(m.CreatedAt)); err != nil {
		return err
	}

	return nil
}

func (m *Configv1MutingRule) contextValidateLabelMatchers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.LabelMatchers); i++ {

		if m.LabelMatchers[i] != nil {

			if swag.IsZero(m.LabelMatchers[i]) { // not required
				return nil
			}

			if err := m.LabelMatchers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("label_matchers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("label_matchers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Configv1MutingRule) contextValidateUpdatedAt(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "updated_at", "body", string(m.UpdatedAt)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Configv1MutingRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Configv1MutingRule) UnmarshalBinary(b []byte) error {
	var res Configv1MutingRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
